---
- name: add repository
  apt_repository: >
    repo=ppa:vbernat/haproxy-1.5 
    state=present

- name: install haproxy
  apt: >
    name={{ item }}
    state=present
  with_items:
   - haproxy
   - socat

- name: copy default configuration
  copy: >
    src=precise/haproxy
    dest=/etc/default/haproxy
  notify: restart haproxy

- name: create configuration
  template: >
    src=precise/haproxy.cfg
    dest=/etc/haproxy/haproxy.cfg
    backup=yes
  notify: restart haproxy

- name: start and enable haproxy
  service: >
    name=haproxy
    state=started
    enabled=yes
